name: AdminMode
version: ${project.version}
main: de.djd001.adminmode.Main
api-version: 1.18
softdepend: [SuperVanish, PremiumVanish, PlaceholderAPI, Luckperms]
commands:
  admin:
    usage: /<command>
    permission: adminmode.admin
    description: Toggle admin mode
  atp:
    usage: /<command> <to>
    permission: adminmode.atp
    description: Teleport to players while being in admin mode
  aconfig:
    usage: /<command>
    permission: adminmode.config
    description: Edit the basic settings
